{% set version = "0.9.0" %}

package:
  name: pandas-datareader
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pandas-datareader/pandas-datareader-{{ version }}.tar.gz
  sha256: b2cbc1e16a6ab9ff1ed167ae2ea92839beab9a20823bd00bdfb78155fa04f891

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  build:
    - python
    - pip
  run:
    - python
    - lxml
    - pandas >=0.21
    - requests >=2.3.0
    - python >=3.6

test:
  imports:
    - pandas_datareader

about:
  home: https://github.com/pydata/pandas-datareader
  license: BSD-3-Clause
  license_file: LICENSE.md
  license_family: BSD
  summary: Up to date remote data access for pandas, works for multiple versions of pandas
  dev_url: https://github.com/pydata/pandas-datareader
  doc_url: https://pandas-datareader.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - mariusvniekerk
    - femtotrader
    - jreback
    - davidastephens
    - bashtage
