{% set name = "pandas-datareader" %}
{% set version = "0.6.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "47681336a3f6e6953b024bd73f8bb005f36e8df831ccce336e9fc601c587e3db" %}
{% set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas
    - requests >=2.3.0
    - requests-file
    - requests-ftp

test:
  imports:
    - pandas_datareader

about:
  home: https://github.com/pydata/pandas-datareader
  license: BSD-3
  license_file: LICENSE.md
  license_family: BSD
  summary: 'Up to date remote data access for pandas, works for multiple versions of pandas'
  dev_url: https://github.com/pydata/pandas-datareader
  doc_url: https://pandas-datareader.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - mariusvniekerk
    - femtotrader
    - jreback
    - davidastephens
    - bashtage
