appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kfSM8XtFMAuUiGKx4ntKEjsk9piiavs4OpCKT+YDk0GydFV1y6PSvPHRiIvaB51yjyjOH4x9D3+7oVS5DB1INEadV98R9dYou4vqgsCJ2md39vu5RWLtnA2um3+B9eYM1T2xSwXx7Mvwj8y5yXYJPyW0EglNkZBO9l7ZAa+QuqvGQSTRtH9xI7EbhiH6jPhkGHSSWZus/W9LysyZkFgA+uXmthVlSPAtQhtM3of1BdPhWa3cRP3nb62UKs9OqrsbUHyYjSsaMrOLVsmU01rdRK7V7vpxiLheupkF79aaqkm3L1mjFjiA1MbFKu5oaCaQA28QkO78YM4U7ulhFjQU4DG1RUSjamo9X9MTwrpdDdedT3fWxPEtZJmtl+EtaLnfO+zTsjZB4JvNDQdqb4sCIe0DdZbHZEVra/TRJyQ+d4be8Lk1Uo2HbGlcRzytZIr1hYjn8oo/k35QSE0DbkhRc2ew1wuBfrH6JCRv1d00Ar4w/iVDJ3kuVsb1gni7xuVV3b62KZD9BrATok9JjNmv3QosACmwF/7m6y0r1nAftvnsSpLnWwBNeoNNy8WYixopBLUGudgkiaTHhUGvoKWFjlsDH2uFRxZp7Mjh/DXC9ACb4hCJ0fdqryQ+SIS6i7Cp2VKrBoIYAMjCGQxudAk4O2kZowKFeGGsRmMQyLP+EmU=}
